[package]
name = "vrlh-power-manager-core"
version = "0.2.0"
authors = ["mass8326"]
edition = "2021"

[lib]
name = "vrlh_power_manager_core"
crate-type = ["lib"]

[dependencies]
futures = "0.3.31"
thiserror = "2.0.12"
tokio = "1.46.1"
btleplug = { version = "0.11.8", features = ["serde"] }
uuid = "1.17.0"
serde = "1.0.219"
async-trait = "0.1.88"
ts-rs = "11.0.1"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
match_bool = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
